version: "2"
services:
  app:
    image: jc21/registry-ui
    ports:
      - 8600:8600
    environment:
      - REGISTRY_HOST=host.docker.internal
      - REGISTRY_SSL=true
      - REGISTRY_DOMAIN=host.docker.internal
      - REGISTRY_STORAGE_DELETE_ENABLED=
    restart: on-failure
